global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: '*inki**@gmail.com'
        from: '***andrey*@yandex.ru'
        smarthost: smtp.yandex.ru:587
        auth_username: '***andrey*@yandex.ru'
        auth_identity: '***andrey*'
        auth_password: '***************'
